AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectName:
    Description: Used as a prefix for project resources.  Can be up to 12 characters, lowercase letters (a-z) only.
    Type: String
    Default: mybookstore
    AllowedPattern: "^[a-z]{1,12}"
    ConstraintDescription: The ProjectName can be up to 12 characters, lowercase letters (a-z) only.

Resources:
  bookstoreVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: '172.31.0.0/16'

  bookstoreSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock:
        Fn::Select:
          - 0
          - Fn::Cidr:
              - Fn::GetAtt: [bookstoreVPC, CidrBlock]
              - 3
              - 8
      VpcId:
        Ref: bookstoreVPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: "AWS::Region"

  bookstoreSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock:
        Fn::Select:
          - 1
          - Fn::Cidr:
              - Fn::GetAtt: [bookstoreVPC, CidrBlock]
              - 3
              - 8
      VpcId:
        Ref: bookstoreVPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: "AWS::Region"

  bookstorePublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      MapPublicIpOnLaunch: true
      CidrBlock:
        Fn::Select:
          - 2
          - Fn::Cidr:
              - Fn::GetAtt: [bookstoreVPC, CidrBlock]
              - 3
              - 8
      VpcId:
        Ref: bookstoreVPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: "AWS::Region"

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-igw

  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref bookstoreVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRoutingTable:
    Type: 'AWS::EC2::RouteTable'
    DependsOn: [AttachInternetGateway]
    Properties:
      VpcId: !Ref bookstoreVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-rtbl-pub

  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRoutingTable

  PublicRouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRoutingTable
      SubnetId: !Ref bookstorePublicSubnet

  bookstoreVPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref bookstoreVPC

  bookstoreVPCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref bookstoreVPCRouteTable
      SubnetId: !Ref bookstoreSubnet1

  bookstoreVPCRouteTableAssociationTwo:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref bookstoreVPCRouteTable
      SubnetId: !Ref bookstoreSubnet2

Outputs:
  ProjectName:
    Value: !Ref ProjectName
    Export:
      Name: !Sub ${AWS::StackName}-ProjectName
  StackName:
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-StackName
  VpcId:
    Value: !Ref bookstoreVPC
    Export:
      Name: !Sub ${AWS::StackName}-VPCID
  VPCCIDRBlock:
    Value: !GetAtt bookstoreVPC.CidrBlock
    Export:
      Name: !Sub ${AWS::StackName}-VPCCIDRBlock
  VPCSecurityGroup:
    Value: !GetAtt bookstoreVPC.DefaultSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-VPCSecurityGroup
  PrivateRouteTable:
    Value: !Ref bookstoreVPCRouteTable
    Export:
      Name: !Sub ${AWS::StackName}-PrivateRouteTable
  PrivateSubnet1:
    Value: !Ref bookstoreSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1
  PrivateSubnet2:
    Value: !Ref bookstoreSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet2
  PublicSubnet:
    Value: !Ref bookstorePublicSubnet
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet
